#!/usr/bin/env bash
if [ `git branch --show-current` == 'main' ]; then
  echo '-------------------------------------'
  echo '| WARNING: commiting on main branch |'
  echo '-------------------------------------'
fi
