name: Go Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
        cache-dependency-path: |
          go.sum

    - run: |
        go build -o /dev/null .
      working-directory: .
