name: Go Check Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
        check-latest: true
        cache-dependency-path: |
          go.sum

    - run: "go fmt ./...; git diff --quiet --exit status"
