name: Go Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
        cache-dependency-path: |
          go.sum
          tools/go.sum

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0

    - run: go vet ./...
