name: Tests on Scraper

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: scraper

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: scraper/go.sum

      - name: Install Staticcheck
        run: go get honnef.co/go/tools/cmd/staticcheck

      - name: Build
        run: |
          go build .

      - name: Test
        run: |
          go test ./...

      - name: Lint
        run: |
          go vet ./...
          go run honnef.co/go/tools/cmd/staticcheck ./...

      - name: Format
        run: ./tests/check-fmt.sh
