name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23"
        check-latest: true
        cache-dependency-path: |
          go.sum
          tools/go.sum

    - run: |
        pwd
        ls
      working-directory: .
