name: Check Type

on:
  push:
    branches: [main]
  pull_request:

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v22.6.0
          cache: npm

      - name: setup
        run: make setup

      - name: Type Check front
        run: npx tsc --noEmit
        working-directory: frontend

      - name: Type Check back
        run: npx tsc --noEmit
        working-directory: backend
